
# Workflow for building and deploying a Next.js site to Firebase
name: Deploy Next.js site to Firebase

on:
  # Runs on pushes targeting the default branch (usually 'main' or 'master')
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# This might not be strictly necessary for Firebase deploy but doesn't hurt.
permissions:
  contents: read
  # For Workload Identity Federation (more advanced, not used in this basic setup with FIREBASE_TOKEN)
  # id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "firebase-deployment" # Changed group name
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Specify your Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        # For App Hosting, environment variables for the build might be needed here
        # For email sending, runtime env vars are set in Firebase Console

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting,apphosting # Deploys both hosting configuration and App Hosting backend
        # If your firebase.json only configures hosting to point to an App Hosting backend,
        # and apphosting.yaml defines the backend, this command should update both.
        # Alternatively, if you manage them separately:
        # firebase deploy --only apphosting # To deploy the backend
        # firebase deploy --only hosting # To deploy hosting rules that point to the backend
